name: Publish release
on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - name: Install cosign
      uses: sigstore/cosign-installer@v3
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and publish
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}